Add usr-lgz mode

diff --git a/tce-estacion/packer/smf/method/fs-root b/tce-estacion/packer/smf/method/fs-root
--- a/tce-estacion/packer/smf/method/fs-root
+++ b/tce-estacion/packer/smf/method/fs-root
@@ -65,7 +65,7 @@ if smf_is_nonglobalzone; then
 fi
 
 /sbin/mount -F ufs -o remount,rw,nologging /devices/ramdisk:a /
-#/usr/sbin/lofiadm -X -a /usr.lgz
+/usr/sbin/lofiadm -a /usr.lgz
 
 #
 # Prior to mounting /usr, devfsadm is not yet available.  As such, we must
@@ -73,19 +73,19 @@ fi
 # path has changed over time so we try both the old (pre-partition support)
 # and new paths.
 #
-#lofi_devices_path='/devices/pseudo/lofi@1:disk'
-#if [ ! -b "$lofi_devices_path" ]; then
-#	lofi_devices_path='/devices/pseudo/lofi@0:1'
-#	if [ ! -b "$lofi_devices_path" ]; then
-#		echo 'could not locate lofi block device in /devices' >&2
-#		exit $SMF_EXIT_ERR_FATAL
-#	fi
-#fi
-#
-#if ! /sbin/mount -F ufs -o ro "$lofi_devices_path" /usr; then
-#	echo "could not mount /usr from $lofi_devices_path" >&2
-#	exit $SMF_EXIT_ERR_FATAL
-#fi
+lofi_devices_path='/devices/pseudo/lofi@1:disk'
+if [ ! -b "$lofi_devices_path" ]; then
+	lofi_devices_path='/devices/pseudo/lofi@0:1'
+	if [ ! -b "$lofi_devices_path" ]; then
+		echo 'could not locate lofi block device in /devices' >&2
+		exit $SMF_EXIT_ERR_FATAL
+	fi
+fi
+
+if ! /sbin/mount -F ufs -o ro "$lofi_devices_path" /usr; then
+	echo "could not mount /usr from $lofi_devices_path" >&2
+	exit $SMF_EXIT_ERR_FATAL
+fi
 
 #
 # Update kernel driver.conf cache with any additional driver.conf
